version: "3"

services:

  app:
    image: nadicadimitrovska/devops-project
    container_name: balloons-devops-project
    ports:
      - 8080:8080
    depends_on:
      - db
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/balloon-shop
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: wp123

  db:
    image: postgres
    container_name: balloons-shop-db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: wp123
      POSTGRES_DB: balloon-shop
    ports:
      - 5432:5432
    volumes:
      - postgres-data:/var/lib/postgresql/data

volumes:
  postgres-data:
