apiVersion: v1
kind: ConfigMap
metadata:
  name: balloon-config
  namespace: balloon-namespace
data:
#  SPRING_DATASOURCE_URL: 'jdbc:postgresql://balloon-store-db.postgres.database.azure.com:5432/balloon-shop'
  SPRING_DATASOURCE_URL: 'jdbc:postgresql://app-service:5432/balloon-shop'
#  'jdbc:postgresql://db:5432/balloon-shop'
#  POSTGRES_USERNAME: 'postgres'
  SPRING_DATASOURCE_USERNAME: 'postgres'
---
apiVersion: v1
kind: Secret
metadata:
  name: balloon-secret
  namespace: balloon-namespace
type: Opaque
data:
  SPRING_DATASOURCE_PASSWORD: d3AxMjM=
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: balloon-deployment
  namespace: balloon-namespace
spec:
  replicas: 1
  selector:
    matchLabels:
      app: devops-project
  minReadySeconds: 25
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1
  template:
    metadata:
      labels:
        app: devops-project
    spec:
      containers:
        - name: devops-project
          image: nadicadimitrovska/devops-project:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
          env:
            - name: SPRING_DATASOURCE_URL
              valueFrom:
                configMapKeyRef:
                  name: balloon-config
                  key: SPRING_DATASOURCE_URL
            - name: SPRING_DATASOURCE_USERNAME
              valueFrom:
                configMapKeyRef:
                  name: balloon-config
                  key: SPRING_DATASOURCE_USERNAME
            - name: SPRING_DATASOURCE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: balloon-secret
                  key: SPRING_DATASOURCE_PASSWORD